# This example configuration outlines how to use the 'cells' subcommand. The base cell configuration is
# for all cells using the 'cell_cfg' subcommand, with the 'cell' subcommand being used to overwrite this
# base configuration for a single cell.

cu_cp:
  amf:
    addr: 127.0.1.100
    port: 38412
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  clock:
  sync:
  srate: 23.04
  otw_format: sc12
  tx_gain: 50
  rx_gain: 60

# Properties set in this section are inherited for all cells unless overridden inside the cells section.
cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1

sib3:
  intra_freq_neigh_cells:
    - nr_pci: 10
      q_offset: 1
    - nr_pci: 20
      q_offset: -4
  intra_freq_black_cells:
    - start: 301
      range: 2
    - start: 401
      range: 0
  intra_freq_white_cells_r16:
    - start: 101
      range: 1
    - start: 204
      range: 2
    - start: 210
      range: 0

# This section is represented as an array of cells. For this example, a single cell is declared that overrides the PCI and channel bandwidth properties from the default values.
cells:
  - pci: 10
    channel_bandwidth_MHz: 10

log:
  filename: /tmp/gnb.log
  all_level: warning

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
