name: Docker Builder
on:
  push:
    branches:
      - main
      - test
  release:
    types: [published]

jobs:
  docker:
    if: ${{ vars.SKIP_DOCKER_JOB != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # --> metrics server
          - TAGNAME: ""
            REPOSITORY: metrics-server
            EXTRA_CMAKE_ARGS: ""
            MARCH: ""
            PLATFORM: amd64
            LIB: ""
            LIB_VERSION: ""
            DOCKERFILE: ./docker/metrics_server/Dockerfile
            CONTEXT: ./docker/metrics_server
          # --> grafana
          - TAGNAME: ""
            REPOSITORY: grafana
            EXTRA_CMAKE_ARGS: ""
            MARCH: ""
            PLATFORM: amd64
            LIB: ""
            LIB_VERSION: ""
            DOCKERFILE: ./docker/grafana/Dockerfile
            CONTEXT: ./docker/grafana
          # --> split72
          # AMD AVX2
          - TAGNAME: split72_release_avx2
            REPOSITORY: srsran-project
            MARCH: x86-64-v3
            PLATFORM: amd64
            LIB: dpdk
            LIB_VERSION: "23.11.1"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
          - TAGNAME: split72_release_with_debug_avx2
            REPOSITORY: srsran-project
            EXTRA_CMAKE_ARGS: -DFORCE_DEBUG_INFO=On
            MARCH: x86-64-v3
            PLATFORM: amd64
            LIB: dpdk
            LIB_VERSION: "23.11.1"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
          # AMD AVX512
          - TAGNAME: split72_release_avx512
            REPOSITORY: srsran-project
            MARCH: x86-64-v4
            PLATFORM: amd64
            LIB: dpdk
            LIB_VERSION: "23.11.1"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
          - TAGNAME: split72_release_with_debug_avx512
            REPOSITORY: srsran-project
            EXTRA_CMAKE_ARGS: -DFORCE_DEBUG_INFO=On
            MARCH: x86-64-v4
            PLATFORM: amd64
            LIB: dpdk
            LIB_VERSION: "23.11.1"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
          # --> split8
          # AMD AVX2
          - TAGNAME: split8_release_avx2
            REPOSITORY: srsran-project
            MARCH: x86-64-v3
            PLATFORM: amd64
            LIB: uhd
            LIB_VERSION: "4.7.0.0"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
          - TAGNAME: split8_release_with_debug_avx2
            REPOSITORY: srsran-project
            EXTRA_CMAKE_ARGS: -DFORCE_DEBUG_INFO=On
            MARCH: x86-64-v3
            PLATFORM: amd64
            LIB: uhd
            LIB_VERSION: "4.7.0.0"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
    env:
      PREFIX: softwareradiosystems/${{ matrix.REPOSITORY }}:${{ matrix.TAGNAME }}
    environment: dockerhub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine tags based on branch
        id: tags
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          DATE_TAG="${GITHUB_SHA:0:10}__$(date +'%Y-%m-%d')"
          RELEASE_NAME_INIT="${{ github.event.release.name }}"
          RELEASE_NAME="${RELEASE_NAME_INIT##* }"

          if [ -n "$RELEASE_NAME" ]; then
            tags="${{ env.PREFIX }}-${DATE_TAG},${{ env.PREFIX }}-${RELEASE_NAME}"
          else
            if [ "$BRANCH_NAME" == "main" ]; then
              tags="${{ env.PREFIX }}-${DATE_TAG},${{ env.PREFIX }}-latest"
            elif [ "$BRANCH_NAME" == "test" ]; then
              tags="${{ env.PREFIX }}-${DATE_TAG},${{ env.PREFIX }}-next"
            fi
          fi
          tags="${tags//:-/:}"
          echo "tags=$tags"
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
          ecr: false

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          file: ${{ matrix.DOCKERFILE }}
          platforms: ${{ matrix.PLATFORM }}
          context: ${{ matrix.CONTEXT }}
          build-args: |
            NAME="${{ env.NAME }}"
            LIB=${{ matrix.LIB }}
            LIB_VERSION=${{ matrix.LIB_VERSION }}
            MARCH=${{ matrix.MARCH }}